config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'comments/create'
  get 'comments/edit'
  get 'comments/update'
  get 'comments/destroy'
  get 'articles/index'
  get 'articles/show'
  get 'users/show'
  get 'pages/team'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'comments/create'
  get 'comments/edit'
  get 'comments/update'
  get 'comments/destroy'
  get 'articles/index'
  get 'articles/show'
  get 'users/show'
  root 'sessions#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'team', to: 'pages#team'
  get 'contact', to: 'pages#contact'
  get 'welcome/:first_name', to: 'pages#welcome', as: 'welcome'
  get 'home', to: 'pages#home'
  get '/signup', to: 'users#new'
  resources :gossips, only: [:show, :new, :create] do
    resources :comments, only: [:create, :destroy]
    member do
      post 'like', to: 'likes#create' 
      delete 'unlike', to: 'likes#destroy'
    end
  end
  
  
  
  resources :users


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
  end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :comments
  has_many :likes, dependent: :destroy
  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  has_many :recipients
  has_many :users, through: :recipients
end

app/models/recipient.rb
class Recipient < ApplicationRecord
  belongs_to :user
  belongs_to :private_message
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :gossip_tags
    has_many :gossips, through: :gossip_tags
  end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :gossips
    has_many :private_messages, foreign_key: 'sender_id'
    has_many :recipients
    has_many :received_messages, through: :recipients, source: 'private_message'
    has_many :likes, dependent: :destroy
  end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
      @gossip = Gossip.find(params[:gossip_id])
      if current_user
        Like.create(gossip: @gossip, user: current_user)
        @gossip.update(likes_count: @gossip.likes.count)
        redirect_to @gossip, notice: "Gossip liked successfully."
      else
        redirect_to @gossip, alert: "Please log in to like this gossip."
      end
    end
  
    def destroy
      @gossip = Gossip.find(params[:gossip_id])
      if current_user
        like = @gossip.likes.find_by(user: current_user)
        like.destroy if like
        @gossip.update(likes_count: @gossip.likes.count)
      end
      redirect_to @gossip
    end
  end
  

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def team
  end
  def contact
  end
  def welcome
    @first_name = params[:first_name]
  end
  def home
    @gossips = Gossip.all

  end
 def show 
  @gossip = Gossip.find(params[:id])
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end
  
    def logged_in?
      !current_user.nil?
    end
  
    def authenticate_user!
      unless logged_in?
        redirect_to login_path, alert: "Please log in first"
      end
    end
  end
  

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="/GossipProject/app/assets/stylesheets/application.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>
  <% unless controller_name == 'sessions' && action_name == 'new' || controller_name == 'users' && action_name == 'new' || controller_name == 'welcome' && action_name == 'index' %>
  <nav class="navbar navbar-expand-lg navbar-light custom-navbar-bg">
    <a class="navbar-brand" href="<%= home_path %>">The Gossip Project</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/team">Team</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/contact">Nous Contacter</a>
        </li>
      </ul>
 
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="<%= signup_path %>">S'inscrire</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= root_path %>">Se deconnecter</a>
        </li>
      </ul>
    </div>
  </nav>
<% end %>

  <body>
    <%= yield %>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

  </body>
</html>

app/views/pages/contact.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Contactez-nous</title>
<style>

  body {
    font-family: Arial, sans-serif;
    background-color: #f0f0f0;
    text-align: center;
  }

  h1 {
    color: #fff; 
    margin-top: 50px;
  }

  p {
    color: #fff; 
  }

  form {
    width: 60%;
    margin: 0 auto;
    padding: 20px;
    background-color: #fff;
    border-radius: 10px;
    box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1);
  }

  label {
    display: block;
    text-align: left;
    margin-bottom: 5px;
    color: #333;
  }

  input[type="text"],
  input[type="email"],
  textarea {
    width: 100%;
    padding: 10px;
    margin-bottom: 15px;
    border: 1px solid #ccc;
    border-radius: 5px;
    box-sizing: border-box;
    font-size: 14px;
  }

  textarea {
    height: 100px;
  }

  button {
    background-color: #4CAF50;
    color: white;
    padding: 10px 20px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    font-size: 16px;
  }

  button:hover {
    background-color: #45a049;
  }
</style>
</head>
<body>

<body class="contact-page">

<h1>Contactez-nous</h1>
<p>Pour toute question ou commentaire, n'hésitez pas à nous contacter en utilisant le formulaire ci-dessous :</p>

<form action="/send_message" method="post">
  <label for="name">Nom :</label>
  <input type="text" id="name" name="name" required>

  <label for="email">Email :</label>
  <input type="email" id="email" name="email" required>

  <label for="message">Message :</label>
  <textarea id="message" name="message" rows="2" required></textarea>

  <button type="submit">Envoyer</button>
</form>

</body>
</html>

app/views/pages/edit.html.erb
<h1>Editer l'article</h1> 

<%= form_for @article do |f| %> 

    <div class="form-group"> 
    <label>Titre de l'article</label> 
    <%= f.tex_field :tilte, class: 'form-control'%> 
    </div> 

    <div class="form-group"> 
    <label>Contenu de l'article</label> 
    <%= f.text_area :content, class: 'form-control' %> 
    </div> 

    <div class="form-group"> 
    <button type="submit">Modifier l'article</button> 
    </div> 

    <% end %>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Wellcome !</title>

  <style>
    .card-container {
      transition: transform 1s ease-in-out;
    }

    .row {
      overflow: hidden;
    }

    
  </style>

  <div class="center-button">
  <button type="button" class="btn btn-primary btn-lg mb-2 custom-button-color">
    <a href="<%= new_gossip_path %>" class="custom-link">BALANCE TON GOSSIP !</a>
  </button>
</div>


 
<div class="container">
  <div class="row">
    <% @gossips.each do |gossip| %>
      <div class="col-md-4 card-container">
        <div class="card mb-3">
          <div class="card-body">
            <h5 class="card-title"><%= gossip.title %></h5>
            <p class="card-text">Par : <%= gossip.user.first_name %></p>
            <p class="card-text"><%= gossip.content %></p>
            <%= link_to "Voir plus", gossip_path(gossip), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>


<script>
  document.addEventListener('DOMContentLoaded', function() {
    var cards = document.querySelectorAll('.card-container');

    function moveCards() {
      var firstCard = cards[0];
      var cardWidth = firstCard.offsetWidth;

      firstCard.style.transform = 'translateX(-' + cardWidth + 'px)';

      setTimeout(function() {
        firstCard.style.transition = 'none';
        firstCard.style.transform = 'translateX(100%)';

        setTimeout(function() {
          firstCard.style.transition = '';
          firstCard.style.transform = '';

          var lastCard = firstCard.parentElement.lastElementChild;
          firstCard.parentElement.insertBefore(lastCard, firstCard.parentElement.firstElementChild);
        }, 100);
      }, 1000);
    }

    setInterval(moveCards, 5000); // Changez 5000 à la durée que vous souhaitez entre chaque défilement (en millisecondes)
  });
</script>





</body>
</html>

app/views/pages/show.html.erb
<h1><%= @article.title %></h1> 

<p><%= @article.content %></p> 

<p>
<a href="<%= articles_path %>" class="btn btn-primary">Revenir aux articles</a> 
</p> 

app/views/pages/team.html.erb
<style> 

..container {
  width: 100%; 
  text-align: center;
}

.rounded-image {
  display: inline-block; 
}

.rounded-image:hover {
  transform: scale(1.1);
  transition: transform 0.3s ease; 
}


.rounded-image img {
  border-radius: 50%;
  margin: 0 auto;
}

h1, h2 {
  color: #fff; 
  text-align: center;
}

h2.name {
  color: #ff0000; 
  text-align: center;
}

</style> 
<body class="team-page">

<div class="container">
  <h1>Le créateur de l'application :</h1>
  <div class="row">
    <div class="col-md-4">
      <div class="rounded-image" id="myPhoto">
        <a href="https://www.youtube.com/watch?v=aLn15rV3_t8" target="_blank">
          <%= image_tag "myphoto.jpeg", class: "card-img-top", alt: "Commercialisation" %>
        </a>
      </div>
      <br>
      <br>
      <h2>Nicolas Baldo</h2>
    </div>
  </div>
</div>

<script>
document.getElementById('myPhoto').addEventListener('click', function() {
  window.location.href = 'https://www.youtube.com/watch?v=aLn15rV3_t8';
});
</script>

app/views/pages/welcome.html.erb
<!-- app/views/pages/welcome.html.erb -->

<h1>BIENVENUE <%= @user %> !</h1>
<p>Te voilà arrivé dans le monde merveilleux de la procrastination</p>